### ISSUE TITLE
Change the title of the header in NavDrawer.vue to match the current page.

### ISSUE THREAD

**Issue by hwanginhanoi** [hwanginhanoi/-.-.-----...-...---------------....------.#22]
Change the title of the header to match the current page.

Line 119 in NavDrawer.vue

<img width="975" alt="image" src="https://github.com/hwanginhanoi/buhbuhbhuh/assets/101512686/fcc8dfa0-bf82-438a-ba9a-f287eb0da59f">

**Comment by khanhdnk** [comment]
Dùng "if" dựa trên link router đc k?

**Comment by jkroflol-rk** [comment]
Resolved in #25
